### ISSUE TITLE
It's nice!

### ISSUE THREAD

**Issue by Sigma711** [wj-111/diary#1]
I reckon the diary is wonderful. It records daily work of your life. When you're old then reading this, you'll feel happy because of seeing your own growth. You're doing a meaningful thing.
I'm so proud of you. The skill of CS Tech is pure, so let the money, stress and other shits go away. Just focus on coding and promote yourself. You're the most worthy one that I recommended to Baidu.

**Comment by wj-111** [comment]
To tell you the truth,read half before I really thought it was a foreigner to leave me a message, until the last word. lol

**Comment by Sigma711** [comment]
Don't be frustrated. Keep practicing. And finally if you can't find a job, maybe I can help you, for example, perhaps I can recommend you to Taichi Graphics.

**Comment by wj-111** [comment]
❤️ you
